/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Color;


/**
 *
 * @author GFS_Mac
 */
public class Inicio extends javax.swing.JFrame {
    
    private ImageIcon imagemLogomarca;
    private ImageIcon imagemEscudo;
    
private void redimensionarImagem(JLabel label, ImageIcon imagemOriginal) {
    if (imagemOriginal != null) {
        int largura = label.getWidth();
        int altura = label.getHeight();
        if (largura > 0 && altura > 0) {
            Image imagemRedimensionada = imagemOriginal.getImage().getScaledInstance(
                    largura, altura, Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(imagemRedimensionada));
        }
    }
}




    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
imagemLogomarca = new ImageIcon(getClass().getResource("/images/PAS.png"));
imagemEscudo = new ImageIcon(getClass().getResource("/images/escudo.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEsq = new javax.swing.JPanel();
        imgLogomarca = new javax.swing.JLabel();
        imgEscudo = new javax.swing.JLabel();
        PanelDir = new javax.swing.JPanel();
        jlb_InformeEmail = new javax.swing.JLabel();
        jlb_InformeEmail.setOpaque(true);
        jlb_InformeEmail.setForeground(Color.WHITE);
        jtxt_campoEmail = new javax.swing.JTextField();
        jbtn_Enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelEsq.setBackground(new java.awt.Color(5, 21, 39));

        imgLogomarca.setAutoscrolls(true);
        imgLogomarca.setMixingCutoutShape(null);
        imgLogomarca.setPreferredSize(new java.awt.Dimension(1077, 544));
        imgLogomarca.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imgLogomarcaComponentResized(evt);
            }
        });

        imgEscudo.setToolTipText("");
        imgEscudo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imgEscudoComponentResized(evt);
            }
        });

        javax.swing.GroupLayout PanelEsqLayout = new javax.swing.GroupLayout(PanelEsq);
        PanelEsq.setLayout(PanelEsqLayout);
        PanelEsqLayout.setHorizontalGroup(
            PanelEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEsqLayout.createSequentialGroup()
                .addGroup(PanelEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEsqLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(imgLogomarca, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEsqLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(imgEscudo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        PanelEsqLayout.setVerticalGroup(
            PanelEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEsqLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(imgLogomarca, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(imgEscudo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        PanelDir.setBackground(new java.awt.Color(30, 53, 118));

        jlb_InformeEmail.setBackground(new java.awt.Color(30, 53, 118));
        jlb_InformeEmail.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        jlb_InformeEmail.setText("Informe o seu e-mail");
        jlb_InformeEmail.setOpaque(true);

        jtxt_campoEmail.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_campoEmail.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        jtxt_campoEmail.setForeground(new java.awt.Color(29, 33, 35));
        jtxt_campoEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxt_campoEmail.setText("e-mail");
        jtxt_campoEmail.setToolTipText("");
        jtxt_campoEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxt_campoEmail.setMargin(new java.awt.Insets(2, 8, 2, 6));
        jtxt_campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_campoEmailActionPerformed(evt);
            }
        });

        jbtn_Enviar.setBackground(new java.awt.Color(98, 189, 235));
        jbtn_Enviar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbtn_Enviar.setForeground(new java.awt.Color(29, 33, 35));
        jbtn_Enviar.setText("Enviar");
        jbtn_Enviar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelDirLayout = new javax.swing.GroupLayout(PanelDir);
        PanelDir.setLayout(PanelDirLayout);
        PanelDirLayout.setHorizontalGroup(
            PanelDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDirLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(PanelDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDirLayout.createSequentialGroup()
                        .addGroup(PanelDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlb_InformeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxt_campoEmail))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDirLayout.createSequentialGroup()
                        .addComponent(jbtn_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );
        PanelDirLayout.setVerticalGroup(
            PanelDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDirLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jlb_InformeEmail)
                .addGap(38, 38, 38)
                .addComponent(jtxt_campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jbtn_Enviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtxt_campoEmail.getAccessibleContext().setAccessibleName("campo para e-mail");
        jtxt_campoEmail.getAccessibleContext().setAccessibleDescription("digite o e-mail");
        jtxt_campoEmail.getAccessibleContext().setAccessibleParent(jlb_InformeEmail);
        jbtn_Enviar.getAccessibleContext().setAccessibleDescription("botão enviar");
        jbtn_Enviar.getAccessibleContext().setAccessibleParent(jlb_InformeEmail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelEsq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEsq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_campoEmailActionPerformed

    private void imgLogomarcaComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imgLogomarcaComponentResized
    redimensionarImagem(imgLogomarca, imagemLogomarca);
    }//GEN-LAST:event_imgLogomarcaComponentResized

    private void imgEscudoComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imgEscudoComponentResized
    redimensionarImagem(imgEscudo, imagemEscudo);
    }//GEN-LAST:event_imgEscudoComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDir;
    private javax.swing.JPanel PanelEsq;
    private javax.swing.JLabel imgEscudo;
    private javax.swing.JLabel imgLogomarca;
    private javax.swing.JButton jbtn_Enviar;
    private javax.swing.JLabel jlb_InformeEmail;
    private javax.swing.JTextField jtxt_campoEmail;
    // End of variables declaration//GEN-END:variables
}
